rbac:
  enabled: true

rbacProxy:
  enabled: true
  logLevel: 10
  imageRepository: gcr.io/kubebuilder/kube-rbac-proxy
  imageTag: v0.4.0
  imagePullPolicy: IfNotPresent
  port: 8443

controller:
  imageRepository: fintechstudios/ververica-platform-k8s-controller
  imageTag: v0.2.0
  imagePullPolicy: IfNotPresent
  metricsAddress: 127.0.0.1:8080
  vpApiUrl: http://ververica-platform-appmanager/api