rbac:
  enabled: true

rbacProxy:
  enabled: true
  logLevel: 10
  imageRepository: gcr.io/kubebuilder/kube-rbac-proxy
  imageTag: v0.4.0
  imagePullPolicy: IfNotPresent
  port: 8443

##  Hyperkube image to use when cleaning up
##
hyperkubeImage:
  repository: k8s.gcr.io/hyperkube
  tag: v1.12.1
  pullPolicy: IfNotPresent

controller:
  imageRepository: fintechstudios/ververica-platform-k8s-controller
  imageTag: v0.3.2
  imagePullPolicy: IfNotPresent
  metricsHost: 127.0.0.1
  metricsPort: 8080
  vpApiUrl: http://ververica-platform-appmanager/api
