run:
  skip-dirs:
    # Don't lint the generated api client
    - appmanager-api-client
    - platform-api-client

output:
  # colored-line-number|line-number|json|tab|checkstyle|code-climate, default is "colored-line-number"
  format: colored-line-number

  # print lines of code with issue, default is true
  print-issued-lines: true

  # print linter name in the end of issue text, default is true
  print-linter-name: true


linters:
  enable:
    - golint
    - gofmt
    - gosec

# golangci.com configuration
# https://github.com/golangci/golangci/wiki/Configuration
service:
  golangci-lint-version: 1.21.x # use the fixed version to not introduce new linters unexpectedly
