apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ template "vp-k8s-operator.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    control-plane: {{ template "vp-k8s-operator.name" . }}-controller-manager
  name: {{ template "vp-k8s-operator.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: {{ template "vp-k8s-operator.name" . }}-controller-manager
  template:
    metadata:
      labels:
        control-plane: {{ template "vp-k8s-operator.name" . }}-controller-manager
    spec:
      containers:
          {{- if .Values.rbacProxy.enabled }}
        - name: kube-rbac-proxy
          image: {{ .Values.rbacProxy.imageRepository }}:{{ .Values.rbacProxy.imageTag }}
          args:
            - --secure-listen-address=0.0.0.0:{{ .Values.rbacProxy.port }}
            - --upstream=http://{{.Values.controller.metricsHost}}:{{.Values.controller.metricsPort}}/
            - --logtostderr=true
            - --v={{ .Values.rbacProxy.logLevel }}
          ports:
            - containerPort: {{ .Values.rbacProxy.port }}
              name: https
          {{- end }}
        - name: manager
          image: {{ .Values.controller.imageRepository }}:{{ .Values.controller.imageTag }}
          imagePullPolicy: {{ .Values.controller.imagePullPolicy }}
          command:
            - /manager
          args:
            - --metrics-addr={{.Values.controller.metricsHost}}:{{.Values.controller.metricsPort}}
            - --platform-api-url={{.Values.controller.platformApiUrl}}
            - --app-manager-api-url={{.Values.controller.appManagerApiUrl}}
          resources:
            limits:
              cpu: 100m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 20Mi
      terminationGracePeriodSeconds: 10
