apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "8443"
    prometheus.io/scheme: https
    prometheus.io/scrape: "true"
  labels:
    control-plane: {{ template "vp-k8s-operator.name" . }}-controller-manager
  name: {{ template "vp-k8s-operator.name" . }}-controller-manager-metrics-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
      {{- if .Values.rbacProxy.enabled }}
    - name: https
      port: {{ .Values.rbacProxy.port }}
      targetPort: https
      {{- end }}
    - name: http
      port: {{ .Values.metricsPort }}
      targetPort: http
  selector:
    control-plane: {{ template "vp-k8s-operator.name" . }}-controller-manager
{{- if .Values.metricsMonitorEnabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: {{ template "vp-k8s-operator.name" . }}-controller-manager
  name: {{ template "vp-k8s-operator.name" . }}-controller-manager-metrics-monitor
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
  - path: /metrics
     {{- if .Values.rbacProxy.enabled }}
    port: https
     {{- else }}
    port: http
     {{- end }}
  selector:
    control-plane: {{ template "vp-k8s-operator.name" . }}-controller-manager
{{- end }}
