rbac:
  enabled: true

rbacProxy:
  enabled: true
  logLevel: 10
  imageRepository: gcr.io/kubebuilder/kube-rbac-proxy
  imageTag: v0.4.1
  imagePullPolicy: IfNotPresent
  port: 8443

imageRepository: fintechstudios/ververica-platform-k8s-operator
imageTag: latest
imagePullPolicy: IfNotPresent

metricsHost: 127.0.0.1
metricsPort: 8080

certs:
  enabled: true

metricsMonitorEnabled: true

vvpUrl: http://ververica-platform-ververica-platform

resources:
  limits:
    cpu: 100m
    memory: 30Mi
  requests:
    cpu: 100m
    memory: 20Mi
