# permissions for end users to view vpdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vpdeployment-viewer-role
rules:
- apiGroups:
  - ververicaplatform.fintechstudios.com
  resources:
  - vpdeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ververicaplatform.fintechstudios.com
  resources:
  - vpdeployments/status
  verbs:
  - get
