# permissions for end users to view vpdeploymenttargets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vpdeploymenttarget-viewer-role
rules:
- apiGroups:
  - ververicaplatform.fintechstudios.com
  resources:
  - vpdeploymenttargets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ververicaplatform.fintechstudios.com
  resources:
  - vpdeploymenttargets/status
  verbs:
  - get
