# permissions for end users to edit vpdeploymenttargets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vpdeploymenttarget-editor-role
rules:
- apiGroups:
  - ververicaplatform.fintechstudios.com
  resources:
  - vpdeploymenttargets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ververicaplatform.fintechstudios.com
  resources:
  - vpdeploymenttargets/status
  verbs:
  - get
