apiVersion: ververicaplatform.fintechstudios.com/v1beta1
kind: VpDeploymentTarget
metadata:
  name: top-speed
  namespace: top-speed
spec:
  metadata:
    # must be `default` for the Community Edition
    namespace: default
  spec:
    kubernetes:
      namespace: top-speed
    deploymentPatchSet:
      - op: add
        path: /hello
        value: gazelle

