# Not supported by the Community Edition
apiVersion: ververicaplatform.fintechstudios.com/v1beta1
kind: VpNamespace
metadata:
  name: top-speed
  namespace: top-speed
spec:
  roleBindings:
    - role: "owner"
      members:
        - "system:authenticated"
