apiVersion: ververicaplatform.fintechstudios.com/v1beta1
kind: VpDeploymentTarget
metadata:
  name: top-speed
  namespace: vvp
spec:
  metadata:
    namespace: testing
  spec:
    kubernetes:
      namespace: vvp
    deploymentPatchSet:
      - op: add
        path: /hello
        value: gazelle

