apiVersion: ververicaplatform.fintechstudios.com/v1beta1
kind: VpDeploymentTarget
metadata:
  name: dep-target-testing
spec:
  metadata:
    namespace: doc-ingestion
  spec:
    kubernetes:
      namespace: flink
    deploymentPatchSet:
      - op: add
        path: "/metadata/annotations/license~1testing"
        value: "true"
