apiVersion: ververicaplatform.fintechstudios.com/v1beta1
kind: VpDeployment
metadata:
  name: deployment
spec:
  deploymentTargetName: dep-target-testing
  metadata:
    namespace: doc-ingestion
  spec:
    state: RUNNING
    upgradeStrategy:
      kind: STATEFUL
    restoreStrategy:
      kind: LATEST_SAVEPOINT
    maxSavepointCreationAttempts: 4
    maxJobCreationAttempts: 4
    template:
      metadata:
        annotations:
          test: "true"
      spec:
        artifact:
          kind: JAR
          jarUri: http://repo1.maven.org/maven2/org/apache/flink/flink-examples-streaming_2.11/1.9.0/flink-examples-streaming_2.11-1.9.0-TopSpeedWindowing.jar
          mainArgs: --windowSize 10 --windowUnit minutes
          entryClass: org.apache.flink.streaming.examples.windowing.TopSpeedWindowing
          flinkVersion: "1.9"
          flinkImageRegistry: registry.platform.data-artisans.net/v2.0
          flinkImageRepository: flink
          flinkImageTag: 1.9.0-stream1-scala_2.11
        parallelism: 1
        numberOfTaskManagers: 1
        resources:
          jobmanager:
            cpu: "1.5"
            memory: 1g
          taskmanager:
            memory: 1.5g
        flinkConfiguration:
          high-availability.storageDir:  s3://flink/haState
          state.savepoints.dir: file:///flink/state/savepoints
          state.checkpoints.dir: file:///flink/state/checkpoints
          taskmanager.numberOfTaskSlots: "1"
        logging:
          log4jLoggers:
            "com.fintechstudios": DEBUG
        kubernetes:
          pods:
#            volumeMounts:
#              - name: config
#                volume:
#                  name: config
#                  configMap:
#                    name: test-configmap
#                volumeMount:
#                  name: config
#                  mountPath: /opt/flink/conf
            annotations:
              "iam.amazonaws.com/role": k8s-flink-job

