
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: vpdeploymenttargets.ververicaplatform.fintechstudios.com
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.metadata.id
    name: Id
    type: string
  - JSONPath: .spec.metadata.resourceVersion
    name: ResourceVersion
    type: integer
  - JSONPath: .spec.metadata.createdAt
    name: Created
    type: date
  - JSONPath: .spec.metadata.modifiedAt
    name: Modified
    type: date
  group: ververicaplatform.fintechstudios.com
  names:
    kind: VPDeploymentTarget
    plural: vpdeploymenttargets
  scope: ""
  subresources: {}
  validation:
    openAPIV3Schema:
      description: VPDeploymentTarget is the Schema for the vpdeploymenttargets API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: VPDeploymentTargetObjectSpec defines the desired state of VPDeploymentTarget
          properties:
            metadata:
              description: VPDeploymentMetadata represents all metadata from the VP
                API
              properties:
                annotations:
                  additionalProperties:
                    type: string
                  type: object
                createdAt:
                  description: Timestamp is a struct that is equivalent to Time, but
                    intended for protobuf marshalling/unmarshalling. It is generated
                    into a serialization that matches Time. Do not use in Go structs.
                  properties:
                    nanos:
                      description: Non-negative fractions of a second at nanosecond
                        resolution. Negative second values with fractions must still
                        have non-negative nanos values that count forward in time.
                        Must be from 0 to 999,999,999 inclusive. This field may be
                        limited in precision depending on context.
                      format: int32
                      type: integer
                    seconds:
                      description: Represents seconds of UTC time since Unix epoch
                        1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to
                        9999-12-31T23:59:59Z inclusive.
                      format: int64
                      type: integer
                  required:
                  - nanos
                  - seconds
                  type: object
                id:
                  type: string
                labels:
                  additionalProperties:
                    type: string
                  type: object
                modifiedAt:
                  description: Timestamp is a struct that is equivalent to Time, but
                    intended for protobuf marshalling/unmarshalling. It is generated
                    into a serialization that matches Time. Do not use in Go structs.
                  properties:
                    nanos:
                      description: Non-negative fractions of a second at nanosecond
                        resolution. Negative second values with fractions must still
                        have non-negative nanos values that count forward in time.
                        Must be from 0 to 999,999,999 inclusive. This field may be
                        limited in precision depending on context.
                      format: int32
                      type: integer
                    seconds:
                      description: Represents seconds of UTC time since Unix epoch
                        1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to
                        9999-12-31T23:59:59Z inclusive.
                      format: int64
                      type: integer
                  required:
                  - nanos
                  - seconds
                  type: object
                name:
                  type: string
                namespace:
                  type: string
                resourceVersion:
                  format: int32
                  type: integer
              type: object
            spec:
              properties:
                kubernetes:
                  description: VPKubernetesTarget allows a user to configure k8s specific
                    options
                  properties:
                    namespace:
                      type: string
                  type: object
              required:
              - kubernetes
              type: object
          type: object
      type: object
  versions:
  - name: v1beta1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
