apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: {{ template "vp-k8s-controller.name" . }}-controller-manager
  name: {{ template "vp-k8s-controller.name" . }}-controller-manager-metrics-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
      {{- if .Values.rbacProxy.enabled }}
    - name: https
      port: {{ .Values.rbacProxy.port }}
      targetPort: https
      {{- end }}
    - name: http
      port: {{ .Values.controller.metricsPort }}
      targetPort: http
  selector:
    control-plane: {{ template "vp-k8s-controller.name" . }}-controller-manager
